---
kind:
  - Troubleshooting
products:
  - Alauda Container Platform
  - Alauda DevOps
  - Alauda AI
  - Alauda Application Services
  - Alauda Service Mesh
  - Alauda Developer Portal
ProductsVersion:
  - 4.1.0,4.2.x
---
<!-- A type of document that involves encountering a fault, diagnosing it, performing root cause analysis, and providing solutions. -->

# 3.4.2

FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: fork/exec ... exec format error unexpected end of JSON input Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds

## Cause
- 当前版本的calico的pod2daemon-flexvol镜像存在问题

## Resolution
- docker load -i pod2daemon-flexvol:v3.16.1.tar.gz
- docker tag pod2daemon-flexvol:v3.16.1.tar.gz xxxx:60080:/xxx/pod2daemon-flexvol:v3.16.1
- docker push xxxx:60080:/xxx/pod2daemon-flexvol:v3.16.1
- kubectl edit ds -n kube-system calico
- 修改calico/pod2daemon-flexvol:v3.16.1镜像拉取规则为Always

## [workaround]

## [Related Information]
**Screenshots**
镜像附件：[![](assets/3-4-2-kubeletbao-cuo-flexvolume-driver-call-failed/placeholder-medium-file.png)pod2daemon-flexvol.tar.gz](/download/attachments/112049085/pod2daemon-flexvol.tar.gz?version=1&modificationDate=1649330385000&api=v2)
- Environment: 3.4.2
- /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds
- pod2daemon-flexvol
- calico
- FlexVolume
- Component: Calico
- Page ID: 112049085
- Original Title: 3.4.2-kubelet报错FlexVolume: driver call failed
